

# simulation test Generated by ai



import numpy as np
from Topology import NetworkManager
from PhysicsEngine import Solver

def run_circuit_simulation():
    print("--- Project Penguin: Multi-Domain Simulation Kernel ---")
    print("--- Scenario: Electrical Bridge Circuit Analysis ---\n")

    # 1. Initialize the Network Manager
    # In this context, the network represents an electrical circuit board.
    circuit_board = NetworkManager()

    # 2. Define System Parameters
    # Mapping General Physics to Electronics:
    #   - Potential        -> Voltage (Volts)
    #   - Flow             -> Current (Amperes)
    #   - Transfer Link    -> Resistor (Ohms)
    #   - Reference Node   -> Ground (GND / 0V)

    # Resistor values in Ohms
    R1 = 10.0  # Top-Left
    R2 = 20.0  # Top-Right
    R3 = 50.0  # The Bridge element (Middle)
    R4 = 30.0  # Bottom-Left
    R5 = 40.0  # Bottom-Right

    # 3. Build the Topology (The Graph)
    # We are building a bridge structure driven by a current source at Node 1.
    
    # Node 1 is the injection point.
    # Current splits into two paths: Node 2 and Node 3.
    circuit_board.add_link(1, 2, R1) # Path 1: 1 -> 2
    circuit_board.add_link(1, 3, R2) # Path 2: 1 -> 3

    # The bridge resistor connecting the two parallel branches.
    circuit_board.add_link(2, 3, R3)

    # Paths to Ground (Reference Node 0)
    circuit_board.add_link(2, 0, R4)
    circuit_board.add_link(3, 0, R5)

    # 4. Initialize the Physics Engine
    # The solver constructs the Conductance Matrix (G).
    engine = Solver(circuit_board)

    # 5. Define Excitations (Input Vector)
    # Applying a Current Source of 2.0 Amperes entering Node 1.
    # Nodes are sorted by ID: [Node 1, Node 2, Node 3]
    # Input Vector I = [2.0A, 0A, 0A]
    
    current_inputs = np.array([2.0, 0.0, 0.0], dtype=np.float64)

    # 6. Solve for System State (Nodal Voltages)
    print(">> Solving Linear System (Gx = i) ...")
    voltages = engine.compute(current_inputs)

    # 7. Display Results
    # Output is technically 'Potential', which we interpret as Voltage.
    print("\n--- Simulation Results ---")
    print(f"Node 1 (Input)   : {voltages[0]:.4f} V")
    print(f"Node 2 (Bridge A): {voltages[1]:.4f} V")
    print(f"Node 3 (Bridge B): {voltages[2]:.4f} V")
    
    # Verification (KCL Check at Node 2)
    # The sum of currents leaving Node 2 must be zero.
    # I_21 + I_23 + I_20 = 0
    # I_xy = (V_x - V_y) / R_xy
    
    v1, v2, v3 = voltages[0], voltages[1], voltages[2]
    
    i_21 = (v2 - v1) / R1
    i_23 = (v2 - v3) / R3
    i_20 = (v2 - 0)  / R4
    
    kcl_residual = i_21 + i_23 + i_20
    print(f"\n[Sanity Check] KCL Residual at Node 2: {kcl_residual:.10f} A (Should be ~0.0)")

if __name__ == "__main__":
    run_circuit_simulation()
